KVM: Protect irq tracing with KVM_HAVE_IOAPIC and KVM_HAVE_PIT
commit acb57be20f6b600848a99796d8f115ec079b8b08
Author: Marcelo Tosatti <mtosatti@redhat.com>
Date:   Wed Jun 17 09:22:14 2009 -0300
    KVM: convert custom marker based tracing to event traces

causes the following compile error on s390:

  CC [M]  arch/s390/kvm/../../../virt/kvm/kvm_main.o
In file included from include/trace/ftrace.h:261,
                 from include/trace/define_trace.h:56,
                 from include/trace/events/kvm.h:55,
                 from arch/s390/kvm/../../../virt/kvm/kvm_main.c:63:
include/trace/events/kvm.h: In function 'ftrace_raw_output_kvm_ack_irq':
include/trace/events/kvm.h:31: error: 'KVM_IRQCHIP_PIC_MASTER' undeclared (first use in this function)
include/trace/events/kvm.h:31: error: (Each undeclared identifier is reported only once
include/trace/events/kvm.h:31: error: for each function it appears in.)
include/trace/events/kvm.h:31: error: 'KVM_IRQCHIP_PIC_SLAVE' undeclared (first use in this function)
include/trace/events/kvm.h:31: error: 'KVM_IRQCHIP_IOAPIC' undeclared (first use in this function)

This patch protects the affected tracers with __KVM_HAVE_IOAPIC and
__KVM_HAVE_PIT.

CC: Marcelo Tosatti <mtosatti@redhat.com>
Signed-off-by: Christian Borntraeger <borntraeger@de.ibm.com>
Signed-off-by: Avi Kivity <avi@redhat.com>