config: fix make kvmconfig
make kvmconfig selects CONFIG_SERIAL_8250 without selecting its
dependencies causing some configs to fail:

drivers/tty/serial/8250/8250.c:57:32: error: 'CONFIG_SERIAL_8250_RUNTIME_UARTS' undeclared here (not in a function)
drivers/tty/serial/8250/8250.c:2712:47: error: 'CONFIG_SERIAL_8250_NR_UARTS' undeclared here (not in a function)
drivers/tty/serial/8250/8250.c: In function 'serial8250_console_write':
drivers/tty/serial/8250/8250.c:2843:10: error: 'struct uart_port' has no member named 'sysrq'
drivers/tty/serial/8250/8250.c: In function 'early_serial_setup':
drivers/tty/serial/8250/8250.c:2971:20: error: negative width in bit-field '<anonymous>'
drivers/tty/serial/8250/8250.c: At top level:
drivers/tty/serial/8250/8250.c:2712:30: warning: 'serial8250_ports' defined but not used [-Wunused-variable]

Fix this by selecting CONFIG_TTY as well, which CONFIG_SERIAL_8250
requires.

Signed-off-by: David Rientjes <rientjes@google.com>
Signed-off-by: Pekka Enberg <penberg@kernel.org>