KVM: use MSR_K7_HWCR for MSRC001_0015 Hardware Configuration Register (HWCR)
MSR_K8_MSR is removed as it is duplicating MSRC001_0015 Hardware
Configuration Register (HWCR), which is already defined as MSR_K7_HWCR

Fix x86_64 allmodconfig :

arch/x86/kvm/svm.c: In function 'svm_set_msr':
arch/x86/kvm/svm.c:2152: error: 'MSR_K8_HWCR' undeclared (first use in this function)

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Jaswinder Singh Rajput <jaswinderrajput@gmail.com>
Signed-off-by: Avi Kivity <avi@redhat.com>