ARM: fiq_debugger: Switch from log_buf_copy to kmsg_dump
In newer kernels, after the global printk rework, there is no such thing
as log_buf_copy anymore. Instead, we should use kmsg_dump helpers. They
also provide a proper _nolock variants, so we don't have to play with
oops_in_progress.

The commit fixes the following build error:

arch/arm/common/built-in.o: In function `end_syslog_dump':
fiq_debugger.c:(.text+0x10a4): undefined reference to `log_buf_copy'
arch/arm/common/built-in.o: In function `dump_kernel_log':
fiq_debugger.c:(.text+0x110c): undefined reference to `log_buf_copy'
make: *** [vmlinux] Error 1

Signed-off-by: Anton Vorontsov <anton.vorontsov@linaro.org>